### ISSUE TITLE
Change the way the plugin works

### ISSUE THREAD

**Issue by williamhatcher** [cuberite/ProtectionAreas#20]
The plugin is designed to prevent players from screwing with protected areas. That's not enough now.

The plugin is incapable of protecting against mobs, tnt, pistons, etc because of the way the areas are loaded into memory. It should load areas into memory as chunks become available, and remove them when they become unloaded (to save memory)
Anytime the table of areas is accessed, it should be updated automatically so we don't have to repeat the same code over and over of making sure the table is up to date (maybe by turning it into a class)

**Comment by bearbin** [comment]
My idea is to maintain the current interface for adding/modifying areas, but to maintain a per chunk "flattened" area table with no intersecting areas, which could be checked against easily. For ease of construction a table mapping areas to chunks could be kept in the database.

I think it would be better to reconstruct the table when adding/modifying areas rather than accessing them, especially as access is much more frequent than modification for perfomance reasons.

**Comment by williamhatcher** [comment]
I am curious as to why overlapping areas are even allowed. Anyone have a clue?

**Comment by bearbin** [comment]
You have a town (only you can build the streets and no mob spawn), you want to allow players to have houses in those towns (allow the player to build there) and some players want to sell shop spaces in their houses (more areas). It is not possible without overlapping areas.

**Comment by williamhatcher** [comment]
I was thinking about something like this
----------
|         |
|    |----------|
|----|---|      |
     |----------|

**Comment by madmaxoft** [comment]
Another reason is purely UX. If the plugin didn't allow overlapping areas, upon defining a new area it would just say "cannot protect area, it overlaps with an existing area", but how does the player fix that, how do they know where is the overlapping area?
